### ISSUE TITLE
Argument "id" has invalid value

### ISSUE THREAD

**Issue by rogermiranda1000** [ihabunek/twitch-dl#155]
Running `./twitch-dl download <id>` with the latest release outputs "Fetching access token... Error: GraphQL query failed. Argument "id" has invalid value <specified_id>. Expected type "ID", found <specified_id>."

**Comment by MonkWho** [comment]
Seeing the same error. I think Twitch changed something a couple days ago and all new videos are throwing this error. I ran some tests and used PirateSoftware channel as a guinea pig since he streams almost every day: 
Video 2146188084 from 2 days ago is working.
Video 2147834644 from today is throwing the same error:

> Fetching video...
> Fetching access token...
> Error: GraphQL query failed.
> * Argument "id" has invalid value 2147834644.
> Expected type "ID", found 2147834644.

**Comment by ihabunek** [comment]
Fix merged and released in v2.3.1. Thanks for reporting.

**Comment by toddfoster** [comment]
Thank you: works great now!
