### ISSUE TITLE
Python code usage documentation

### ISSUE THREAD

**Issue by lodenrogue** [ihabunek/twitch-dl#31]
Do you have any documentation how to use this library inside of python code? Method names, etc.

**Comment by ihabunek** [comment]
No, sorry, you'll need to read the code. It's not that complex. If you describe what you'd like to do maybe I can help.

**Comment by BluelyTASer** [comment]
I was been using this since 2020/08/27 with the command to download videos by reading the code since i can't find any usage documentation and now I have like 5.017T of downloaded Twitch Streams! :O
![1381](https://user-images.githubusercontent.com/59511669/96351670-7428cd00-1093-11eb-9057-942e455311aa.PNG)

**Comment by scatalfo** [comment]
> No, sorry, you'll need to read the code. It's not that complex. If you describe what you'd like to do maybe I can help.

I'm having the same issue, how would you go about downloading singular clips within a Python program?
