### ISSUE TITLE
override temp dir?

### ISSUE THREAD

**Issue by lilywastaken** [ihabunek/twitch-dl#32]
particularly large vods may pose an issue on Linux where by default temp files are stored in memory. I've seen some vods well over 10GB, would require over 20GB of memory (by default) to store it all in tmpfs

**Comment by garoto** [comment]
what about:

`TMP=/my/alt/tmp/path/ twitch-dl download <VOD>`

**Comment by ihabunek** [comment]
@lilywastaken Like @garoto suggested, you can override the temp dir using the `TMP` env variable. `TMPDIR` and `TEMP` also work. This is due to using [tempfile.gettempdir](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir).

I'll leave this issue open as a reminder to document this.

**Comment by ihabunek** [comment]
https://github.com/ihabunek/twitch-dl#temporary-files

**Comment by garoto** [comment]
For Windows, one can setup a doskey macro like below:

```
> doskey /macros | rg twitc
twitch-dl=cmd /d /c "setlocal & set "TMPDIR=J:\TMP" & @twitch-dl.exe $*"
twitch-dl.exe=cmd /d /c "setlocal & set "TMPDIR=J:\TMP" & @twitch-dl.exe $*"
```

Apparently, overriding %TEMP% or %TMP% environmetal variables don't work with doskey macros, but python's `TMPDIR` is a nice workaround (if not defined early I assume, not sure).
