### ISSUE TITLE
File name stripping first digit of VOD ID

### ISSUE THREAD

**Issue by MobiusReactor** [ihabunek/twitch-dl#60]
When downloading vods, the resultant filename is missing the first digit of the vod ID.

For example, downloading https://www.twitch.tv/videos/878573493 results in the file "20210118_78573493_baertaffy_1_streamer_on_twitch_makes_inglorious_return.mp4"

Tested using 1.15.0 on WSL as well as natively on a linux box. Not sure when exactly this started happening, because it didn't happen with an older version.

**Comment by KryptonicDragon** [comment]
This appears to be intentional, or at least an oversight:
https://github.com/ihabunek/twitch-dl/blob/2242af05fc9565fcc3a627a137d7776bbaee1abd/twitchdl/commands/download.py#L76

And it seems to have been that way for at least 2 years: https://github.com/ihabunek/twitch-dl/commit/da60560b637afdf4e92de0859c0f30b9dfb4481f

**Comment by ihabunek** [comment]
Ah. This was written while using the kraken api which prefixes IDs with an underscore. I switched to graphql and didn't remove the slice. I'll fix it up.
