### ISSUE TITLE
[Feature Request] Support for storing metadata in mkv files

### ISSUE THREAD

**Issue by miff2000** [ihabunek/twitch-dl#80]
It would be useful to store the stream metadata in the resultant `.mkv` files that `twitch-dl` produces. It seems like it might be simple enough to do, though it would add a dependency on `mutagen` or similar perhaps (assuming `ffmpeg` can't do it)

Would you have any objections to this support being added? Are all Twitch streams recorded in a container format like MKV?

**Comment by miff2000** [comment]
Any thoughts on accepting a PR for this @ihabunek

**Comment by ihabunek** [comment]
I like the idea. Implemented in [1.17.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.17.0).

I used ffmpeg options `-metadata title="foo"` and `-metadata artist="bar"`. That should work on containers which support metadata.

Twitch streams are not in MKV, they're VODs, but I convert them to MKV by default since it's a reasonable format. You can change it by passing`--format=mp4` or whatever when downloading the video.

**Comment by miff2000** [comment]
Thank you for this. I've used it a few times and it's worked great!
